[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# irc = { #git = "https://github.com/MCT32/rust-irc.git", tag = "0.0.3" }
irc = { path = "../rust-irc" }
tokio = { version = "1.36", features = ["full"] }
crossterm = { version = "0.27.0", features = ["event-stream"] }
rand = "0.8.5"
colored = "2.1.0"
